from FSI.fsi_inspections_data_mining_export_excel import inspection_data_mining_fsi
from FSI.fsi_question_level_export_excel import question_level_fsi
from AO.ao_inspections_data_mining_export_excel import inspection_data_mining_ao
from AO.ao_question_level_export_excel import question_level_ao
from email_service import email_sender

inspection_data_mining_fsi()
question_level_fsi()
inspection_data_mining_ao()
question_level_ao()
email_sender()